version: 2
jobs:

  integrate:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: Environment
          command: |
            git --version
            env | sort | grep "CIRCLE"
      - run:
          name: Intro
          command: ./play --manuscript .circleci/manuscript.yml --part gitintro
      - run:
          name: Swap to target branch and test integration
          command: ./play --manuscript .circleci/manuscript.yml --part integrate

  jekyll-build:
    working_directory: /app
    docker:
      - image: lakruzz/jekyll-plus:1.0.1
    steps:
      - restore_cache:
          keys:
            - the-repo-{{ .Revision }}
      - run:
          name: Build Jekyll
          command: |
            export JEKYLL_PARAMS=`printenv CIRCLE_BRANCH | grep -e "^master$" && echo "--config _config.yml,_stage_config.yml" || echo ""`
            printenv JEKYLL_PARAMS
            jekyll build $JEKYLL_PARAMS
      - save_cache:
          key: the-built-repo-{{ .Revision }}
          paths:
            - _site
            - .circleci

  deliver:
    working_directory: /app
    docker:
      - image: lakruzz/play:latest
    steps:
      - restore_cache:
          keys:
            - the-repo-{{ .Revision }}
      - run:
          name: Deliver
          command: play --manuscript .circleci/play-proflow-cci-gh.yml --part deliver
          
  deploy_dev:
    docker:
      - image: circleci/node:8.10
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install Firebase Tools
          command: sudo npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: Deploy to dev
          command: sudo ./firebase-deploy/node_modules/.bin/firebase deploy --only hosting -P development --token=$FIREBASE_TOKEN

workflows:
  version: 2
  projectsProlikeIo:
    jobs:
      - integrate:
          filters:
            branches:
              only:
                - /ready\/.+/
      - jekyll-build:
          requires:
            - integrate
      - deliver:
          requires:
            - jekyll-build
          filters:
             branches:
               only:
                - /ready\/.+/
      - deploy_dev: # Staging
          requires:
            - jekyll-build
          filters:
             branches:
               only:
                - master
